package com.docly.app.ui.util

object DoclyTestTags {
    const val SCANNER_SCREEN = "scanner_screen"
    const val REVIEW_SCREEN = "review_screen"
    const val EDITOR_SCREEN = "editor_screen"
    const val METADATA_SCREEN = "metadata_screen"
    const val EXPORT_SCREEN = "export_screen"
    const val LIBRARY_SCREEN = "library_screen"

    const val NAVIGATE_BACK_ACTION = "navigate_back_action"
    const val OPEN_LIBRARY_ACTION = "open_library_action"
    const val CAMERA_PREVIEW = "camera_preview"
    const val DOCUMENT_BOUNDARY_OVERLAY = "document_boundary_overlay"
    const val CAMERA_PERMISSION_ACTION = "camera_permission_action"
    const val CAMERA_SETTINGS_ACTION = "camera_settings_action"
    const val CAMERA_CAPTURE_ACTION = "camera_capture_action"
    const val CAMERA_FLASH_TOGGLE = "camera_flash_toggle"
    const val IMPORT_SINGLE_PHOTO_ACTION = "import_single_photo_action"
    const val IMPORT_MULTIPLE_PHOTOS_ACTION = "import_multiple_photos_action"
    const val REVIEW_EDITOR_ACTION = "review_editor_action"
    const val EDITOR_METADATA_ACTION = "editor_metadata_action"
    const val METADATA_EXPORT_ACTION = "metadata_export_action"
    const val EXPORT_LIBRARY_ACTION = "export_library_action"
    const val LIBRARY_SCANNER_ACTION = "library_scanner_action"
    const val REVIEW_PAGE_THUMBNAIL = "review_page_thumbnail"
    const val REVIEW_CROP_OVERLAY = "review_crop_overlay"
    const val REVIEW_CROP_TOP_LEFT_HANDLE = "review_crop_top_left_handle"
    const val REVIEW_CROP_TOP_RIGHT_HANDLE = "review_crop_top_right_handle"
    const val REVIEW_CROP_BOTTOM_RIGHT_HANDLE = "review_crop_bottom_right_handle"
    const val REVIEW_CROP_BOTTOM_LEFT_HANDLE = "review_crop_bottom_left_handle"
    const val REVIEW_RESET_DETECTED_ACTION = "review_reset_detected_action"
    const val REVIEW_RESET_FULL_IMAGE_ACTION = "review_reset_full_image_action"
    const val REVIEW_APPLY_CROP_ACTION = "review_apply_crop_action"
    const val EDITOR_PAGE_THUMBNAIL = "editor_page_thumbnail"
    const val LIBRARY_DOCUMENT_THUMBNAIL = "library_document_thumbnail"

    const val LOADING_CONTENT = "loading_content"
    const val ERROR_CONTENT = "error_content"
    const val EMPTY_CONTENT = "empty_content"
}
